'''
Created on 03 dic 2015

@author: stefanopetrangeli
'''
import requests, json, logging, random
from orchestrator_core.config import Configuration
from orchestrator_core.userAuthentication import UserData, UserAuthentication
from orchestrator_core.controller import UpperLayerOrchestratorController
from nffg_library.nffg import NF_FG
from nffg_library.validator import ValidateNF_FG
from orchestrator_core.sql.domains_info import DomainInformation

#username = 'AdminPoliTO'
#password = 'AdminPoliTO'
#tenant = 'PoliTO_chain1'

username = 'admin'
password = 'admin'
tenant = 'admin_tenant'

conf = Configuration()

# set log level
if conf.DEBUG is True:
    log_level = logging.DEBUG
    requests_log = logging.getLogger("requests")
    requests_log.setLevel(logging.WARNING)
    sqlalchemy_log = logging.getLogger('sqlalchemy.engine')
    sqlalchemy_log.setLevel(logging.WARNING)
elif conf.VERBOSE is True:
    log_level = logging.INFO
    requests_log = logging.getLogger("requests")
    requests_log.setLevel(logging.WARNING)
else:
    log_level = logging.WARNING

log_format = '%(asctime)s %(levelname)s %(message)s - %(filename)s'

logging.basicConfig( filename="../"+conf.LOG_FILE, level=log_level, format=log_format, datefmt='%m/%d/%Y %I:%M:%S %p')
logging.debug("Script Starting")


#in_file = open("/home/stack/Documents/LiClipse Workspace/frog4/grafo0.json","r")
#in_file = open("/home/stack/Documents/LiClipse Workspace/frog4/grafo0_AR.json","r")
#in_file = open("/home/stack/Documents/LiClipse Workspace/frog4/grafo1.json","r")
in_file = open("../../frog4/grafo_giacomo.json","r")
in_file = open("../../frog4/grafo_giacomo_Hy.json","r")
#in_file = open("../../frog4/grafo_ODL_VLAN_Hy.json","r")

#in_file = open("../../frog4/UN/PhysicalPortsWithVlan.json","r")
in_file = open("../../frog4/grafo2.json","r")
in_file = open("../../frog4/grafo3_4vnf_annotated.json","r")
in_file = open("../../frog4/grafo3_4vnf_annotated_far.json","r")
in_file = open("../../frog4/grafo2_far.json","r")
in_file = open("../../frog4/grafo_ivano.json","r")
#in_file = open("../../frog4/nffg_extensions.json","r")

#in_file = open("../../frog4/jolnet_endp.json","r")
#in_file = open("../../frog4/jolnet_connection.json","r")
#in_file = open("../../frog4/UNs_jolnet/candidate.json","r")


#in_file = open("../../frog4/jolnet_graphHe_3endp.json")
#nf_fg_file = {"forwarding-graph":{"id":"1","end-points":[{"id":"1_1","vlan":{"switch-id":"00:00:34:db:fd:3c:11:40","interface":"5109","vlan-id":"2"},"type":"vlan","name":"autogenerated_split_000000005"},{"id":"1_2","vlan":{"switch-id":"00:00:64:e9:50:5a:87:c0","interface":"5097","vlan-id":"2"},"type":"vlan","name":"autogenerated_split_000000005"},{"id":"2_1","vlan":{"switch-id":"00:00:34:db:fd:3c:11:40","interface":"5109","vlan-id":"3"},"type":"vlan","name":"autogenerated_split_000000008"},{"id":"2_2","vlan":{"switch-id":"00:00:64:e9:50:5a:87:c0","interface":"5097","vlan-id":"3"},"type":"vlan","name":"autogenerated_split_000000008"},{"id":"3_1","vlan":{"switch-id":"00:00:34:db:fd:3c:11:40","interface":"5109","vlan-id":"4"},"type":"vlan","name":"autogenerated_split_000000011"},{"id":"3_2","vlan":{"switch-id":"00:00:64:e9:50:5a:87:c0","interface":"5097","vlan-id":"4"},"type":"vlan","name":"autogenerated_split_000000011"}],"big-switch":{"flow-rules":[{"id":"1_1","priority":10,"match":{"port_in":"endpoint:1_1"},"actions":[{"output_to_port":"endpoint:1_2"}]},{"id":"1_2","priority":10,"match":{"port_in":"endpoint:1_2"},"actions":[{"output_to_port":"endpoint:1_1"}]},{"id":"2_1","priority":10,"match":{"port_in":"endpoint:2_1"},"actions":[{"output_to_port":"endpoint:2_2"}]},{"id":"2_2","priority":10,"match":{"port_in":"endpoint:2_2"},"actions":[{"output_to_port":"endpoint:2_1"}]},{"id":"3_1","priority":10,"match":{"port_in":"endpoint:3_1"},"actions":[{"output_to_port":"endpoint:3_2"}]},{"id":"3_2","priority":10,"match":{"port_in":"endpoint:3_2"},"actions":[{"output_to_port":"endpoint:3_1"}]}]}}}
#nf_fg_file ={"forwarding-graph":{"id":"4","name":"Forwarding graph","VNFs":[{"vnf_template":"example.json","id":"00000001","name":"firewall","ports":[{"id":"inout:0"},{"id":"inout:1"}],"domain":"un_ti"},{"vnf_template":"example.json","id":"00000002","name":"firewall1","ports":[{"id":"inout:0"},{"id":"inout:1"}],"domain":"un_ve"},{"vnf_template":"example.json","id":"00000003","name":"firewall2","ports":[{"id":"inout:0"},{"id":"inout:1"}],"domain":"un_ve"}],"end-points":[{"id":"00000001","name":"user","type":"interface","interface":{"interface":"eth1"},"domain":"un_ti"},{"id":"00000002","name":"internet","type":"interface","interface":{"interface":"eth2"},"domain":"un_ve"}],"big-switch":{"flow-rules":[{"id":"000000001","priority":10,"match":{"port_in":"endpoint:00000001"},"actions":[{"output_to_port":"vnf:00000001:inout:0"}]},{"id":"000000002","priority":10,"match":{"port_in":"vnf:00000001:inout:0"},"actions":[{"output_to_port":"endpoint:00000001"}]},{"id":"000000003","priority":15,"match":{"port_in":"vnf:00000001:inout:1","protocol":"0x06"},"actions":[{"output_to_port":"vnf:00000002:inout:0"}]},{"id":"000000004","priority":15,"match":{"port_in":"vnf:00000002:inout:0","protocol":"0x06"},"actions":[{"output_to_port":"vnf:00000001:inout:1"}]},{"id":"000000005","priority":10,"match":{"port_in":"vnf:00000001:inout:1"},"actions":[{"output_to_port":"vnf:00000003:inout:0"}]},{"id":"000000006","priority":10,"match":{"port_in":"vnf:00000003:inout:0"},"actions":[{"output_to_port":"vnf:00000001:inout:1"}]},{"id":"000000007","priority":15,"match":{"port_in":"vnf:00000002:inout:1","protocol":"0x06"},"actions":[{"output_to_port":"vnf:00000003:inout:0"}]},{"id":"000000008","priority":15,"match":{"port_in":"vnf:00000003:inout:0","protocol":"0x06"},"actions":[{"output_to_port":"vnf:00000002:inout:1"}]},{"id":"000000009","priority":10,"match":{"port_in":"vnf:00000003:inout:1"},"actions":[{"output_to_port":"endpoint:00000002"}]},{"id":"000000010","priority":10,"match":{"port_in":"endpoint:00000002"},"actions":[{"output_to_port":"vnf:00000003:inout:1"}]}]}}}
#nf_fg_file={"forwarding-graph":{"end-points":[{"id":"user_in","vlan":{"vlan-id":"202","interface":"eth1"},"type":"vlan"},{"id":"user_out","vlan":{"vlan-id":"203","interface":"eth1"},"type":"vlan"}],"VNFs":[{"unify-env-variables":[{"variable":"whateverasdasdas2=somethingelseasdasd2"},{"variable":"whatever2=somethingelse2"}],"id":"FW1","name":"firewall","vnf_template":"VPNPP-FW-Private.json","ports":[{"id":"L2Port:0"},{"id":"L2Port:1"},{"id":"L2Port:2"}]}],"id":"102","name":"Jolnet Firewall TI 2.1","big-switch":{"flow-rules":[{"priority":500,"id":"1A","match":{"port_in":"endpoint:user_in"},"actions":[{"output_to_port":"vnf:FW1:L2Port:0"}]},{"priority":500,"id":"1B","match":{"port_in":"vnf:FW1:L2Port:0"},"actions":[{"output_to_port":"endpoint:user_in"}]}]}}}

a= in_file.read()
nf_fg_file = json.loads(a)

ValidateNF_FG().validate(nf_fg_file)
nffg = NF_FG()
nffg.parseDict(nf_fg_file)

logging.debug(nffg.getJSON())
controller = UpperLayerOrchestratorController(user_data=UserData(username, password, tenant))
controller.put(nffg)
#print (controller.get(41))
#controller.delete(100)
#print (controller.get(4))
#controller.delete(4)
#controller.delete(2)
#controller.delete(21)
#controller.getStatus(977)
#controller.delete(977)
#controller.delete(51)
#controller.delete(250)
#controller.delete(52)
#controller.delete(977)
#controller.delete(4)
#controller.delete("3_base")

print('Job completed')
exit()

orchestrator_endpoint = "http://127.0.0.1:9000/NF-FG/%s"
graph = "http://127.0.0.1:9000/NF-FG/2"
graph_status = "http://127.0.0.1:9000/NF-FG/status/4"
headers = {'Accept': 'application/json', 'Content-Type': 'application/json', 
           'X-Auth-User': username, 'X-Auth-Pass': password, 'X-Auth-Tenant': tenant}
#requests.put(orchestrator_endpoint % nffg.id, json.dumps(nf_fg_file), headers=headers)
#requests.delete(graph, headers=headers)
resp = requests.get(graph_status, headers=headers)
print(resp.text)

print('Job completed')
